version: '3.3'
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data:
networks:
  sonarnet:
    driver: bridge
services:
  postgresdb:
    image: postgres
    networks:
      - sonarnet
    ports:
      - '15432:5432'
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - sonarnet
  sonarqubesonar:
    image: sonarqube:latest
    ports:
      - '9000:9000'
      - '9092:9092' 
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://postgresdb:5432/sonar
    #command: sysctl -w vm.max_map_count=262144
    ulimits:
      nofile:
        soft: 65535
        hard: 65535  
      memlock:
        soft: -1
        hard: -1
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
