## Este docker-compose é executado uma única vez no setup do ambiente
# para criação dos diretórios de dados para IBFT e gerar as chaves dos validadores
version: '3.5'

services:
  ## INITIALIZE DATA FOLDERS AND GENERATE VALIDATOR KEYS
  node-1:
    image: 0xpolygon/polygon-edge:latest
    command: ["secrets", "init", "--data-dir", "/data"]
    ports:
      - '10000:9632'
      - '10002:8545'
    volumes:
      - ~/sgbds/polygon-edge/node-1:/data
      - ~/sgbds/polygon-edge/genesis:/genesis
    networks:
      - polygon-edge-docker
    restart: on-failure
    
  node-2:
    image: 0xpolygon/polygon-edge:latest
    command: ["secrets", "init", "--data-dir", "/data"]
    ports:
      - '20000:9632'
      - '20002:8545'
    volumes:
      - ~/sgbds/polygon-edge/node-2:/data
      - ~/sgbds/polygon-edge/genesis:/genesis
    networks:
      - polygon-edge-docker
    restart: on-failure
    
  node-3:
    image: 0xpolygon/polygon-edge:latest
    command: ["secrets", "init", "--data-dir", "/data"]
    ports:
      - '30000:9632'
      - '30002:8545'
    volumes:
      - ~/sgbds/polygon-edge/node-3:/data
      - ~/sgbds/polygon-edge/genesis:/genesis
    networks:
      - polygon-edge-docker
    restart: on-failure
    
  node-4:
    image: 0xpolygon/polygon-edge:latest
    command: ["secrets", "init", "--data-dir", "/data"]
    ports:
      - '40000:9632'
      - '40002:8545'
    volumes:
      - ~/sgbds/polygon-edge/node-4:/data
      - ~/sgbds/polygon-edge/genesis:/genesis
    networks:
      - polygon-edge-docker
    restart: on-failure

networks:
  polygon-edge-docker:
    driver: bridge
    name: polygon-edge-docker

volumes:
  node-1:
  node-2:
  node-3:
  node-4:
  genesis: