version: "3.3"

services:
  anaconda: 
    image: store/continuumio/anaconda:4.0.0
    #shm_size: 1g
    ports:
      - "8888:8888"
    volumes:
      - ~/sgbds/anaconda/notebooks/:/home/notebooks
    #command: sh -c "jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root
    entrypoint: ["jupyter-notebook","--ip=0.0.0.0","--port=8888","--notebook-dir=/home/notebooks"]