version: '3.3'
volumes:
  mongodata:
  mongoconfig:
services:
  mongodb:
    image: mongo:4.4.2
    container_name: 'mongoMain'
    ports:
      - '27017:27017'
    volumes:
      - /home/fabianorodrigo/sgbds/mongodb/main/db:/data/db
      - /home/fabianorodrigo/sgbds/mongodb/main/configdb:/data/configdb
    environment:
      - MONGO_INITDB_DATABASE=main
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mongoexpress:
    image: mongo-express:latest
    links:
      - mongodb
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
