version: '3.3'

services:
  postgresdb: #quando for acessar via pgadmin, esse é o nome do host
    image: postgres:13
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres} #seta variável de ambiente POSTGRES_USER ou fica com o default
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme} #seta variável de ambiente POSTGRES_PASSWORD ou fica com o default
      - PGDATA=/var/lib/postgresql/data/main
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ~/sgbds/postgres13/data:/var/lib/postgresql/data
    networks:
      - postgresnet
networks:
  postgresnet:
    driver: bridge
volumes:
  postgresql:
  postgresql_data:
  pgadmin:
